baseURL = "http://localhost:1313"
theme = "whisper"
languageCode = "en-us"
title = "Hugo Whisper Theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_docs_button_link = '/docs'
  homepage_docs_button_text = 'Read The Docs'
  homepage_source_button_link = 'https://github.com/TibbyRocks/Tibby'
  homepage_source_button_text = 'Get the Source'
  fontawesomekit = "e042207efc"

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true


  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"

  [params.footer]
    copyright_text = 'Copyright 2024 - The end of Time, TibbyRocks | Theme by <a class="zerostatic" href="https://www.zerostatic.io">Zerostatic</a>'
